version: "3.7"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ambassador
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
  #    networks:
  #      - postgres
  #    volumes:
  #      - .dbdata:/var/lib/postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


#networks:
#  postgres:
#    driver: bridge

volumes:
  postgres: